//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationWaiver
    {
        public int EntryID { get; set; }
        public string ApplicationID { get; set; }
        public string ApplicantSignature { get; set; }
        public string SignatureDate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
