//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingLicense
    {
        public int ID { get; set; }
        public string ApplicationID { get; set; }
        public string DL_Number { get; set; }
        public string DL_State { get; set; }
        public string DL_Type { get; set; }
        public System.DateTime DL_ExpirationDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
